### ISSUE TITLE
Confused as to how to use this package in my configuration

### ISSUE THREAD

**Issue by mattiasdrp** [mohkale/consult-company#3] opened 2022-08-29 13:40 UTC
I'm sure this is a noob question but here it is:

In my current setup, when I hit `tab` and company is enabled, it will execute `company-indent-or-complete-common` and not `complete-at-point`. I'm using this because I'm adding a lot of informations to my completion candidates as you can see here:

![image](https://user-images.githubusercontent.com/5543639/187213025-6bb2c66c-c884-43c5-82d8-4428af2fc8bd.png)

I tried adding:

```elisp
  (use-package consult-company
    :ensure t
    :config
    (define-key company-mode-map [remap completion-at-point] #'consult-company))
```

But if I use completion-at-point it executes completion-at-point and I have to use consult-company to have the proper result. The issue is that it's not plugged to my company setup:

![image](https://user-images.githubusercontent.com/5543639/187214689-483f14f7-8f74-4e47-9da8-fca8fd57c485.png)

Is there a way to use it only to sort company candidates while still using the company functions?

**Comment by mohkale** [comment] 2022-08-29 13:47
@mattiasdrp 

I'm not completely sure what you're asking for here.

> Is there a way to use it only to sort company candidates while still using the company functions?

What does this mean? Do you just want the minibuffer completion while copy pasting the candidates as is from the company popup? I.E. no grouping by snippet or word.

**Comment by mattiasdrp** [comment] 2022-08-29 14:56
I'd like to have the same extended display that your package gives (with the grouping) but with the extended definitions of candidates provided by company as shown in my first screenshot

**Comment by mohkale** [comment] 2022-08-29 18:30
So you just want the completion annotations on company also in the minibuffer? The `type t = string ....` that company shows? That seems like a good feature, I'm surprised it isn't already but likely just because I haven't encountered it before and use this package infrequently enough that I've never noticed the need.

**Comment by mohkale** [comment] 2022-08-29 19:40
@mattiasdrp 

Please try the changes in the newly created PR and let me know if it meets your use cases now.

![Screenshot_20220829_203938](https://user-images.githubusercontent.com/23294780/187284308-f354b276-cf88-4bda-9106-6955c971cbd0.png)

**Comment by mattiasdrp** [comment] 2022-08-30 16:03
Sorry for the late answer.

It works well :-)

The thing is I'd like to have the sorting and grouping you do but plugged to company. My tab key is bound to `company-ident-or-complete-common` and this function is not used by `complete-at-point`. I guess the easiest way would be for me to implement my custom sorting function with grouping and add it in vertico multiform, no?

**Comment by mattiasdrp** [comment] 2022-08-30 16:20
To be a bit more clear I have two ways to start a company action: 
- write a character and company will start automatically and give me candidates
- hit tab and company will try to indent and if the line is already indented it will give me candidates

Currently candidates are sorted by their length which is not really useful and your mode actually creates a nice grouping so I thought I could plugged it directly to company candidates but `consult-company` does everything:
- complete common
- gather candidates
- sort them
- call company finish on the sorted candidates

My issue then is that I don't understand where I can plug it to make it work with my current setup.

**Comment by mohkale** [comment] 2022-08-30 18:28
@mattiasdrp 

> To be a bit more clear I have two ways to start a company action
> ...
> My issue then is that I don't understand where I can plug it to make it work with my current setup.

This package isn't designed to replace either of those workflows, it's designed to provide a new one you can use however you'd like. Personally I rarely use consult-company, and almost always use the standard company popup. When there's something I expect to be a completion candidate, but it isn't showing up with the dialog (or typing a common prefix would take too long), then I fallback to consult-company. The added more powerful filtering with orderless (and the other support commands) almost always provides a better experience but it takes me out of the regular insertion process so I use it sparingly.

I'd recommend building an approach you like, rather than asking for mine. If this package doesn't support that workflow then you can open a new ticket do discuss the value of supporting it. I can't exactly tell you what process you'd be most comfortable with.

> Currently candidates are sorted by their length which is not really useful and your mode actually creates a nice grouping so I thought I could plugged it directly to company candidates

Sorting isn't something that should be implemented in this package. We already pass a `:sort` value of nil to consult--read which should make it keep the default order of completions shown by company. If it's sorting by length then it's because company is sorting by length and we're just inheriting that. For example I use precient for sorting and its resorted the company-candidates by recent completions which is intern reflected in consult-company:

![Screenshot_20220830_191934](https://user-images.githubusercontent.com/23294780/187513463-d8b1e221-f2dd-4168-8491-505ff601c746.png)

![Screenshot_20220830_191943](https://user-images.githubusercontent.com/23294780/187513487-f377e080-b0c1-4bc1-b656-a74c67c5cbcd.png)

If you don't like this default sorting you can set a custom sort function for consult-company with `consult-customize`. If you come with one that you believe is useful enough to everyone else please open a PR and share it with the community. You can also set a sort function for individual completion categories which I just realised hasn't been supported by this package because we don't set a category, that should be fixed with the referenced PR and you can find a description for how to do it in the consult wiki.

In regards to grouping with the company dialog (which you seem to be referencing) I have no idea how that would work but I'd suggest asking on the company repository instead of here.

I'm going to go ahead and merged the referenced PR and close this issue since you've confirmed it's working as expected. Feel free to continue responding here if you want to discuss more.

**Comment by mohkale** [comment] 2022-08-30 18:32
S.N. If you wan't consult-company to run with tab have you considered `(define-key company-active-map [tab] 'consult-company)`?

**Closed as completed** 2022-08-30 18:34 UTC

**Comment by mattiasdrp** [comment] 2022-08-30 20:06
Thanks for the answer. I'll try to come up with something that suits me and show it to you for further discussion to avoid bothering you more with my questions :D 

Have a nice evening/day/night/... :-)
